name: MICA
channels:
  - pytorch3d-nightly
  - pytorch
  - iopath
  - fvcore
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - alsa-lib=1.2.3=h516909a_0
  - blas=1.0=mkl
  - bottleneck=1.3.4=py38hce1f21e_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.4.26=h06a4308_0
  - cairo=1.16.0=ha12eb4b_1010
  - certifi=2022.6.15=py38h06a4308_0
  - cffi=1.15.0=py38hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.10.0=py38_0
  - cython=0.29.28=py38h295c915_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2.30.0=py_0
  - dbus=1.13.6=h5008d03_3
  - decorator=4.4.2=py_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.3.2=h37c90e5_3
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.96=h8e229c2_2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.11.0=h70c0345_0
  - fvcore=0.1.5.post20210915=py38
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.5=hf529b03_3
  - gstreamer=1.18.5=h9f60fe5_3
  - harfbuzz=3.4.0=hb4a5f5f_0
  - hdf5=1.12.1=h69dfa17_1
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.9.0=py_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=py38
  - jasper=2.0.33=ha77e612_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9d=h7f8727e_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.2.0=py38hfd86e86_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=13.0.1=default_hc23dcda_0
  - libcurl=7.82.0=h7bff187_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_14
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.70.2=h174f98d_4
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm13=13.0.1=hf817b99_2
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.5.5=py38hd60e7aa_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=hbc83047_0
  - libpq=14.2=hd57d9b9_0
  - libprotobuf=3.19.4=h780b84a_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_14
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.3.0=h6f004c6_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h166bdaf_1014
  - llvm-openmp=13.0.1=he0ac6c6_1
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-base=3.3.1=py38h817c723_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mysql-common=8.0.28=haf5c9bc_2
  - mysql-libs=8.0.28=h28c427c_2
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.5=py_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.76=h2350873_0
  - numexpr=2.8.1=py38h6abb31d_0
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - opencv=4.5.5=py38h578d9bd_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1o=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.1=py38h295c915_1
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.0.1=py38h22f2fdc_0
  - pip=21.2.4=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - portalocker=2.4.0=py38h578d9bd_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.5=py38he5a9106_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=py_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.6.1=py38_cu113_pyt1110
  - pytz=2021.3=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyyaml=5.3.1=py38h7b6447c_1
  - qt=5.12.9=ha98a1a1_5
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - scikit-image=0.17.2=py38hdf5156a_0
  - scipy=1.7.3=py38hc147768_0
  - setuptools=61.2.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.2=hc218d9a_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - termcolor=1.1.0=py_2
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.12=h27826a3_0
  - toolz=0.11.1=py_0
  - torchaudio=0.11.0=py38_cu113
  - torchvision=0.12.0=py38_cu113
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.63.1=pyhd8ed1ab_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wget=1.20.1=h20c2e04_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - absl-py==1.1.0
    - albumentations==1.2.0
    - cachetools==5.2.0
    - chumpy==0.70
    - easydict==1.9
    - flatbuffers==2.0
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - importlib-metadata==4.12.0
    - insightface==0.6.2
    - joblib==1.1.0
    - loguru==0.6.0
    - markdown==3.3.7
    - oauthlib==3.2.0
    - onnx==1.12.0
    - onnxruntime==1.11.0
    - opencv-python-headless==4.6.0.66
    - prettytable==3.3.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - qudida==0.0.4
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.1.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - trimesh==3.12.7
    - wcwidth==0.2.5
    - werkzeug==2.1.2
    - zipp==3.8.0
prefix: /home/wzielonka/miniconda3/envs/MICA
